USB-Userport: Userport.c File Reference
Userport.c File Reference
USB-Userport main file.
#include "Userport.h"
Functions
bool CALLBACK_HID_Device_CreateHIDReport (USB_ClassInfo_HID_Device_t *const HIDInterfaceInfo, uint8_t *const ReportID, const uint8_t ReportType, void *ReportData, uint16_t *const ReportSize)
void CALLBACK_HID_Device_ProcessHIDReport (USB_ClassInfo_HID_Device_t *const HIDInterfaceInfo, const uint8_t ReportID, const uint8_t ReportType, const void *ReportData, const uint16_t ReportSize)
void EVENT_USB_Device_ConfigurationChanged (void)
void EVENT_USB_Device_Connect (void)
void EVENT_USB_Device_ControlRequest (void)
void EVENT_USB_Device_Disconnect (void)
void EVENT_USB_Device_StartOfFrame (void)
int main (void)
void SetupHardware (void)
Variables
USB_ClassInfo_HID_Device_t Generic_HID_Interface
static uint16_t IRQmaskGPIO1
static uint16_t IRQmaskGPIO2
static uint16_t previousGPIO1
static uint16_t previousGPIO2
Detailed Description
USB-Userport main file.
Main source file for the USB-Userport. This file contains the main tasks and the control logic.
Function Documentation
CALLBACK_HID_Device_CreateHIDReport()
bool CALLBACK_HID_Device_CreateHIDReport (USB_ClassInfo_HID_Device_t *const HIDInterfaceInfo, uint8_t *const ReportID, const uint8_t ReportType, void * ReportData, uint16_t *const ReportSize)
HID class driver callback function for the creation of HID reports to the host. This is where the USB-IN-reports (device to host) are created. With LUFA's HID class implementation this is also where Feature-IN-reports (device to host) get created. Depending on ReportType and ReportID the respective answer is prepared. A special consideration need the INTERRUPT-IN reports, sending the asynchronous data to the host and getting build here in addition. In this case the requested Report-ID is '0'. Well, this is special and needs more thoughts. Since the USB-host actively samples each device for such asynchronous data it is not really asynchronous to the bus. And since any INTERRUPT-IN data must wait until the host asks for it, it is also not really interrupting. The best way to think of it is a kind of universal request for unspecific data the device decides to send (or not). The host receives this and forwards it to the application. From the application view this report is not requested and interrupts the application processing.
Note
There is some timeout limitation and any reaction shall get returned within this limit. Otherwise the host will detect a device issue.
Parameters
[in] HIDInterfaceInfo Pointer to the HID class interface configuration structure being referenced.
[in,out] ReportID Report ID requested by the host if non-zero, otherwise its the INTERRUPT IN poll.
[in] ReportType Type of the report to create, either HID_REPORT_ITEM_In or ID_REPORT_ITEM_Feature.
[out] ReportData Pointer to a buffer where the created report should be stored.
[out] ReportSize Number of bytes written in the report (or zero if no report is to be sent).
Returns
Boolean true to force the sending of the report, false to not send it. Library automatics are overriden due to ReportID usage.
References ADC_Chan_4, ADC_Chan_5, ADC_Chan_6, ADC_Chan_7, ADC_Get_Sample(), GPIO1_GetDirections(), GPIO1_GetLines(), GPIO2_GetDirections(), GPIO2_GetLines(), io_read(), IRQmaskGPIO1, IRQmaskGPIO2, LEDs_GetAll(), previousGPIO1, previousGPIO2, REPORT_ID_DEVICE_LEDS, REPORT_ID_DIRS_GPIO1, REPORT_ID_DIRS_GPIO2, REPORT_ID_GET_ADC4, REPORT_ID_GET_ADC5, REPORT_ID_GET_ADC6, REPORT_ID_GET_ADC7, REPORT_ID_IRQ_GPIO, REPORT_ID_IRQEN_GPIO, REPORT_ID_LINES_GPIO1, REPORT_ID_LINES_GPIO2, REPORT_ID_MEM_ACCESS, REPORT_SIZE_DEVICE_LEDS, REPORT_SIZE_GET_ADC, REPORT_SIZE_GET_GPIO, REPORT_SIZE_IRQ_GPIO, REPORT_SIZE_IRQEN_GPIO, RXLED, RXLED_POS, TXLED, and TXLED_POS.
CALLBACK_HID_Device_ProcessHIDReport()
void CALLBACK_HID_Device_ProcessHIDReport (USB_ClassInfo_HID_Device_t *const HIDInterfaceInfo, const uint8_t ReportID, const uint8_t ReportType, const void * ReportData, const uint16_t ReportSize)
HID class driver callback function for the processing of HID reports from the host. This is where the USB-OUT-reports (host to device) are processed, depending on ReportType and ReportID. LUFA's HID class implementation also ends up here when the host sends a Feature-OUT-report.
Parameters
[in] HIDInterfaceInfo Pointer to the HID class interface configuration structure being referenced.
[in] ReportID Report ID of the received report from the host.
[in] ReportType The type of report that the host has sent, either HID_REPORT_ITEM_Out or HID_REPORT_ITEM_Feature.
[in] ReportData Pointer to a buffer where the received report has been stored.
[in] ReportSize Size in bytes of the received HID report.
References ADC_Configure(), GPIO1_ChangeDirections(), GPIO1_ChangeLines(), GPIO2_ChangeDirections(), GPIO2_ChangeLines(), IRQmaskGPIO1, IRQmaskGPIO2, LEDS_NO_LEDS, LEDs_SetAll(), REPORT_ID_DEVICE_LEDS, REPORT_ID_DIRS_GPIO1, REPORT_ID_DIRS_GPIO2, REPORT_ID_IRQEN_GPIO, REPORT_ID_LINES_GPIO1, REPORT_ID_LINES_GPIO2, REPORT_ID_MEM_ADR, REPORT_ID_SERVO_PWM, REPORT_ID_SET_ADC, RXLED, RXLED_POS, TXLED, and TXLED_POS.
EVENT_USB_Device_ConfigurationChanged()
void EVENT_USB_Device_ConfigurationChanged (void)
Event handler for the library USB Configuration Changed event. Unchanged with respect to the LUFA generic HID demo.
References Generic_HID_Interface.
EVENT_USB_Device_Connect()
void EVENT_USB_Device_Connect (void)
Event handler for the library USB Connection event. Currently this is empty.
EVENT_USB_Device_ControlRequest()
void EVENT_USB_Device_ControlRequest (void)
Event handler for the library USB Control Request reception event. Unchanged with respect to the LUFA generic HID demo.
References Generic_HID_Interface.
EVENT_USB_Device_Disconnect()
void EVENT_USB_Device_Disconnect (void)
Event handler for the library USB Disconnection event. Currently this is empty.
EVENT_USB_Device_StartOfFrame()
void EVENT_USB_Device_StartOfFrame (void)
Event handler for the USB device Start Of Frame event. Unchanged with respect to the LUFA generic HID demo.
References Generic_HID_Interface.
main()
int main (void)
Main program. First it initializes some hardware. The complete activity then is performed by an endless loop calling some tasks.
References Generic_HID_Interface, and SetupHardware().
SetupHardware()
void SetupHardware (void)
Initializes the USB-Userport.
References GPIO1_GetLines(), GPIO2_GetLines(), GPIO_Init(), IRQmaskGPIO1, IRQmaskGPIO2, LEDs_Init(), previousGPIO1, and previousGPIO2.
Variable Documentation
Generic_HID_Interface
USB_ClassInfo_HID_Device_t Generic_HID_Interface
Initial value:
=
   {
      .Config =
         {
            .InterfaceNumber              = INTERFACE_ID_GenericHID,
            .ReportINEndpoint             =
               {
                  .Address                = GENERIC_IN_EPADDR,
                  .Size                   = GENERIC_EPSIZE,
                  .Banks                  = 1,
               },
            .PrevReportINBuffer           = NULL,
            .PrevReportINBufferSize       = GENERIC_REPORT_SIZE,
         },
   }
LUFA HID Class driver interface configuration and state information. This structure is passed to all HID Class driver functions, so that multiple instances of the same class within a device can be differentiated from one another.
IRQmaskGPIO1
uint16_t IRQmaskGPIO1 static
contains the change monitor control bitmask for GPIO1.
IRQmaskGPIO2
uint16_t IRQmaskGPIO2 static
contains the change monitor control bitmask for GPIO2.
previousGPIO1
uint16_t previousGPIO1 static
tracks the previous line state for change detection on GPIO1.
previousGPIO2
uint16_t previousGPIO2 static
tracks the previous line state for change detection on GPIO2.