# * The USB-Userport *
# Copyright 2020  René Trapp (rene [dot] trapp (-at-) web [dot] de)
# License: "The MIT license" - see license.txt'

# Default target
all: docu

docu:
	c:\Program Files\doxygen\bin\doxygen.exe ./Doxyfile_eng
	c:\Program Files\doxygen\bin\doxygen.exe ./Doxyfile_deu
